### ISSUE TITLE
物品栏按钮无新版贴图

### ISSUE THREAD

**Issue by WhiteElephant-abc** [fifth-light/TouchController#100]
国际基岩版（1.21.51.02）中，物品栏按钮为半透明

**Comment by fifth-light** [comment]
> 物品栏按钮为半透明

![Java 版中快捷栏](https://github.com/user-attachments/assets/6f9a4ddb-72d2-4411-a077-44f48815e38c)

Java 版中快捷栏为不透明的，因此我打算将物品栏按钮也做成不透明的。


其实我并不打算完全复刻基岩版的物品栏按钮的渲染，因为仔细放大看，你会发现像素根本就不对齐：

![基岩版中的快捷栏](https://github.com/user-attachments/assets/7b8f728c-216d-4a32-bfa7-3756bf3dc8b2)

![放大后的基岩版物品栏按钮](https://github.com/user-attachments/assets/63928406-27a1-4662-a340-87f97c81b8b1)

![放大后的基岩版物品栏按钮，加上了辅助线](https://github.com/user-attachments/assets/2bc07e1c-d93d-4677-9d1c-48852c0af881)

**Comment by WhiteElephant-abc** [comment]
那就算了
