### ISSUE TITLE
下蹲按钮不符合基岩版操作

### ISSUE THREAD

**Issue by WhiteElephant-abc** [fifth-light/TouchController#101]
在国际基岩版1.21.51.02中，点击一下下蹲按钮即可下蹲，再次点击即可取消，而此模组需要双击
如果基岩版旧版本就是双击，那么建议在关闭经典外观后改为新版控制逻辑

**Comment by WhiteElephant-abc** [comment]
实测现版本TC的潜行按钮逻辑为基岩版1.21.51.02中方向按键中心潜行按钮的逻辑（即双击）

**Comment by fifth-light** [comment]
> 基岩版旧版本就是双击

是这样的。

> 关闭经典外观后改为新版控制逻辑

commit fda3761382da24be43c4befa5479b9a2f06ecd3e

**Comment by WhiteElephant-abc** [comment]
> > 基岩版旧版本就是双击
> 
> 是这样的。
> 
> > 关闭经典外观后改为新版控制逻辑
> 
> commit [fda3761](https://github.com/fifth-light/TouchController/commit/fda3761382da24be43c4befa5479b9a2f06ecd3e)

好快的修
