### ISSUE TITLE
摇杆不符合基岩版逻辑

### ISSUE THREAD

**Issue by WhiteElephant-abc** [fifth-light/TouchController#105]
1. 在国际基岩版1.21.51.02中，摇杆不能通过点击触发，必须拖动才能识别
2. 半透明的按钮会在激活时提高不透明度

**Comment by fengzhou0w0** [comment]
@fifth-light 我其实挺喜欢TC现在的摇杆逻辑。假如未来计划将摇杆与基岩版保持同步特性，我建议将现在的逻辑做成可选择的编辑项。

**Comment by fifth-light** [comment]
> 我其实挺喜欢TC现在的摇杆逻辑。假如未来计划将摇杆与基岩版保持同步特性，我建议将现在的逻辑做成可选择的编辑项。

行，我拆分为激活时透明度改变和移动激活两个选项

**Comment by WhiteElephant-abc** [comment]
> > 摇杆不能通过点击触发，必须拖动才能识别
> 
> 想了一下，这个移动激活的逻辑目前无法实现，我就只实现透明度改变吧

那够了
