### ISSUE TITLE
错误的按键间隙

### ISSUE THREAD

**Issue by WhiteElephant-abc** [fifth-light/TouchController#107]
初始的顶部两个按键并没有空隙，而国际基岩版1.21.51.02中有一定的间隙
物品栏按钮并没能像基岩版一样融入物品栏

**Comment by fifth-light** [comment]
> 物品栏按钮并没能像基岩版一样融入物品栏

如果合并进物品栏会影响和其他 mod 的兼容性。

**Comment by fifth-light** [comment]
> 初始的顶部两个按键并没有空隙，而国际基岩版1.21.51.02中有一定的间隙

我参考的老版基岩版没有间隙。考虑到按键贴图默认是老版贴图，我认为没有间隙是正常行为。
