### ISSUE TITLE
view movement by finger has fps freezes

### ISSUE THREAD

**Issue by alexchalmov** [fifth-light/TouchController#112]
it looks like fps drops while looking around with finger. you can see this issue better on 120hz screen. if i enable mouse movement in mod settings and set sensitivity to 100 (or delete mod at all) view movement became smooth. the fps drops even more when using boat (the fps in game is stable 120, the fps drops is visible only by the eye )

**Comment by alexchalmov** [comment]
The minecart also can't be driven by touch controller buttons

**Comment by fifth-light** [comment]
What launcher and mod version are you using? In the latest mod v0.0.12 and launcher I updated them to use Unix domain socket which should perform better.

**Comment by fifth-light** [comment]
I tested on my Huawei MatePad 11 with TouchController v0.0.12 and the latest build of launcher, can't reproduce this problem

**Comment by alexchalmov** [comment]
I use pojavlauncher 20241220 from your release post and v0.0.12 mod version. My phone is nubia z60 ultra (snapdragon 8gen3) Display info app shows 780hz touch sampling rate of my touchscreen. I use vsync in game and alternative visualizer in launcher settings for normal vsync work. I see low touch sampling rate in game with mod also at 60hz and 120hz screen mode

**Comment by fifth-light** [comment]
I rechecked the code on the launcher side. PojavLauncher and FoldCraftLauncher don't use IPC; they run Minecraft and the launcher in the same process. However, my mod uses Unix domain socket IPC to send input events between the game and the launcher, which may introduce lags or janks and are highly device-dependent (specifically, kernel-dependent).

In the future, I may introduce a better way to communicate between the game and the launcher if they are in the same process. But for now, you can try switching to another device to see if it performs any better.
