### ISSUE TITLE
同步基岩版显示上的一些小细节

### ISSUE THREAD

**Issue by yqs112358** [fifth-light/TouchController#119]
如发现在显示细节上有一些可改进的地方，有助于让手感更贴近真实的基岩版。简单录了个短视频：

https://github.com/user-attachments/assets/83d8a504-f286-470a-9332-3455d89ef80e

1. 基岩版在手指触摸的准心位置有“方块高亮”的效果，挖掘或者点击方块的时候同样如此，这可以显著提高触摸的反馈感
2. 基岩版挖掘方块时，圆圈中间的挖掘进度指示器不是从零开始变大的，而是一开始就有一定的半径。这应该是照顾玩家的手指有一定粗细，更便于观察

**Comment by fifth-light** [comment]
第一点与 #94 重复。我重复一下我在 #94 说的话：

> 我之前就想这么做，但是发现不知道如何渲染这种效果，最后就决定还是用java版的边框效果吧。
>
> 如果有谁知道做可以指导一下，我是不会做了。

第二点可以考虑。具体从多少开始好？

**Comment by yqs112358** [comment]
确实🤣🤣

第二个相对没那么重要，可以从半径1/3或者一半开始

**Comment by fifth-light** [comment]
> 可以从半径1/3或者一半开始

我默认一半，然后提供一个设置可以调节起始大小吧。

**Comment by fifth-light** [comment]
方块高亮目前不实现

第二点完成于 commit 2a564a7d6a01b8565164ca9470006093d858e97e
