### ISSUE TITLE
[Bug] 无法加载配置屏幕

### ISSUE THREAD

**Issue by EatHatsuneShallots** [fifth-light/TouchController#121]
版本：e282a68954a5bc7a6c76da7fc9b08ffc4a1ed538（Debug 版）
日志：
无法提供更多信息
```
[23:03:54] [Render thread/WARN]: The 'touchcontroller' mod config screen is not available because androidx/collection/MutableScatterSet is missing.
```

**Comment by fifth-light** [comment]
你跑的不是 commit e282a689 吧，估计是 combine 分支里的构建。combine 分支还在开发，不能使用都是正常情况，试试 0.0 分支看看？

**Comment by fifth-light** [comment]
已在 commit da9d71fd93c4902b9453e079204cd554561d1c23 中修复。但是我再强调一遍，combine 分支目前正在开发中，新配置界面功能还没有完全实现甚至缺失，可能会出现各种问题，一般游玩我还是建议使用 0.0 分支为好。

**Comment by EatHatsuneShallots** [comment]
> 你跑的不是 commit e282a689 吧

好像是我无脑选了 Action 里的最新版（没看分支）

**Comment by EatHatsuneShallots** [comment]
> 已在 commit da9d71fd93c4902b9453e079204cd554561d1c23 中修复

经测试未修复，仍能复现

**Comment by fifth-light** [comment]
> 经测试未修复，仍能复现

我测试 Github Actions 里自动编译的 commit da9d71fd93c4902b9453e079204cd554561d1c23 可以使用，你是自己编译的吗？

**Comment by EatHatsuneShallots** [comment]
> 我测试 Github Actions 里自动编译的 commit da9d71fd93c4902b9453e079204cd554561d1c23 可以使用，你是自己编译的吗？

可能是我用的从 GitHub Actions 里的旧版（下载的文件名一模一样，都是 `Artifacts.zip`）
经测试未能复现（已校验文件完整性）
