### ISSUE TITLE
Inventory button doesn't close menus

### ISSUE THREAD

**Issue by alexchalmov** [fifth-light/TouchController#134]
Can't close inventory/chest and etc menus with inventory button, only open. Button "E" in pojavlauncher works for opening and closing inventory, button in touchcontroller mod works only for opening. Is it possible to simply bind the "E" key to the inventory button? And another question: is it possible to disable touches in the game at the locations of the pojavlauncher buttons? When I click on the button, the touch is also transferred to the game.

**Comment by fifth-light** [comment]
duplicate with #25 and #71: I will add a close button for all GUI instead

For your second question, you can try other launcher instead.

**Comment by Handsomeprin** [comment]
> 不能用库存按钮关闭库存/箱子等菜单，只能打开。pojavlauncher 中的按钮“E”用于打开和关闭库存，touchcontroller mod 中的按钮仅用于打开。是否可以简单地将“E”键绑定到库存按钮？还有另一个问题：是否可以在游戏中的 pojavlauncher 按钮位置禁用触摸？当我点击按钮时，触摸也会转移到游戏中。

you can try flod craft launcher:https://fcl.ningmo.fun/download.html

**Comment by WhiteElephant-abc** [comment]
> > 不能用库存按钮关闭库存/箱子等菜单，只能打开。pojavlauncher 中的按钮“E”用于打开和关闭库存，touchcontroller mod 中的按钮仅用于打开。是否可以简单地将“E”键绑定到库存按钮？还有另一个问题：是否可以在游戏中的 pojavlauncher 按钮位置禁用触摸？当我点击按钮时，触摸也会转移到游戏中。
> 
> you can try flod craft launcher:https://fcl.ningmo.fun/download.html

翻译都给引用进来了（）
