### ISSUE TITLE
提供一个 Android 库给安卓端的启动器使用

### ISSUE THREAD

**Issue by fifth-light** [fifth-light/TouchController#37]
当时编写 TouchController 只是为了满足同学联机的需求，很感谢主线 PGW (Vera-Firefly/Pojav-Glow-Worm@a1d9e5c6368ac35e46196bffe3edcd2854c481cc) 和尚未合并进入主线的 FCL (FCL-Team/FoldCraftLauncher@2ec72ab87da2ce41b6009c3f7c275a4a503646dd) 还有主线 ZalithLauncher (ZalithLauncher/ZalithLauncher@4f517de15ed757a5a1012be700de0ca6c696726a) 对 TouchController 提供了官方的支持。

我一开始的确打算提供一个库，但是由于当时尝试 Minecraft 端实现 Unix 套接字没能成功，索性开摆了。因此当时修改 PojavLauncher 和 FCL 是采取的是能用就行，Quick&Dirty 的方法，留下了三个问题：

- 代码组织不好（PGW 和 FCL 两个启动器的官方支持都对代码重新进行了组织）
- 不支持发送物品栏处的点击到游戏（使 #35 无法实现）
- 本地回环 UDP 这个办法虽然可行，但是安全和可靠性上存在问题

考虑到日后要增加震动支持（#10），为安卓端启动器提供一个支持库是合理的，这样既可以避免安卓端的启动器直接使用本地回环端口上的 UDP 连接这种临时方法（日后打算使用自行编译的动态库，重新添加对 Unix 套接字的支持），也可以统一启动器之间对新功能（例如震动等）的实现。

这个 issue 计划提供一个新库 proxy-client-android，包含一个 TouchControllerLayout（继承自 FrameLayout），只需要将游戏界面相关的 View 包含在内即可发送触控消息到 TouchController。如果应用不想使用 TouchControllerLayout，想要手动处理 MotionEvent，这个库也会提供相应的方法来辅助 Android 端启动器适配 TouchController。

原有的 proxy-client 库仍然会保留，用来提供一些高级用例（例如屏幕串流客户端一侧运行 proxy-client，服务端一侧运行 TouchController，让不支持多点触控的串流软件也可使用 TouchController）的支持。

**Comment by WhiteElephant-abc** [comment]
所以PojavLauncher也会官方支持TC？

**Comment by WhiteElephant-abc** [comment]
哦PGW不是PojavLauncher

**Comment by fifth-light** [comment]
目前已基本完成，正在测试中

**Comment by fifth-light** [comment]
已经发布在 Maven Central 上为 `top.fifthlight.touchcontroller:proxy-client-android:0.0.2`

**Comment by WhiteElephant-abc** [comment]
所有FCL现在可以官方支持了？

**Comment by fifth-light** [comment]
> 所有FCL现在可以官方支持了？

不着急，我没这么说过，FCL 支持还在分支里没进入主线

**Comment by WhiteElephant-abc** [comment]
_这不是给启动器提供的库嘛_
