### ISSUE TITLE
更新mod后配置丢失

### ISSUE THREAD

**Issue by WhiteElephant-abc** [fifth-light/TouchController#39]
启动器：FCL
平台：安卓
mod版本：0.0.7--->0.0.8
在模组管理中检查更新并更新mod后键位变为初始配置
同时还更新了fabric API

**Comment by WhiteElephant-abc** [comment]
[fcl-exported-logs-2024-12-16T23-54-18[1].log](https://github.com/user-attachments/files/18153142/fcl-exported-logs-2024-12-16T23-54-18.1.log)
这是shi'y使用fcl“导出启动器日志”功能生成的日志
.minecraft的我找一下

**Comment by WhiteElephant-abc** [comment]
不对我修改版启动器中的mc装到私有目录了...

**Comment by WhiteElephant-abc** [comment]
[2024-12-15-6.log.gz](https://github.com/user-attachments/files/18153283/2024-12-15-6.log.gz)
有一个latest是不是要删..bin啊

**Comment by WhiteElephant-abc** [comment]
[latest.log](https://github.com/user-attachments/files/18153299/latest.log)
不然GitHub不让传（）

**Comment by fifth-light** [comment]
我知道问题发生的原因了，是一个竞态条件

**Comment by WhiteElephant-abc** [comment]
修的好快！

**Comment by fifth-light** [comment]
> 修的好快！

其实后来发现还有问题，发了个 v0.0.10 作为修复
