### ISSUE TITLE
显示按键名称

### ISSUE THREAD

**Issue by WhiteElephant-abc** [fifth-light/TouchController#42]
在添加按键或选中按键时显示按键名称（就是作用）
因为java版玩家或基岩版高版本玩家对添加按键时显示的UI并不熟悉

**Comment by fifth-light** [comment]
合并到 #26

**Comment by fifth-light** [comment]
![目前的进度](https://github.com/user-attachments/assets/1466edc1-c9be-4fdd-b28a-ed302166b656)
目前的进度
