### ISSUE TITLE
更多预设

### ISSUE THREAD

**Issue by WhiteElephant-abc** [fifth-light/TouchController#56]
现在的默认配置，如果想使用摇杆需要增加下蹲按键，并且摇杆初始大小过小，需要手动调整，很是麻烦
建议添加两种默认配置，一种是按键一种是摇杆，便于新玩家上手，或重置键位后快速地配置（同时如果真的添加，建议摇杆预设全部使用新版贴图）

**Comment by fifth-light** [comment]
这样吧，关于自定义布局的问题实在太多，全部汇总到 #26 内吧
