### ISSUE TITLE
调试选项并非默认折叠

### ISSUE THREAD

**Issue by WhiteElephant-abc** [fifth-light/TouchController#58]
注意到在全局设置和物品设置中，选项分类都可以折叠，那么其中调试选项何不改成默认折叠或者放到子页面中

**Comment by fifth-light** [comment]
马上干

**Comment by fifth-light** [comment]
![效果](https://github.com/user-attachments/assets/beca7859-359a-4174-820a-7e320309198e)
在 commit cf11eba83618df3de94492f8271ac86accec39e7 中修复
