### ISSUE TITLE
“取消”按钮会直接退出模组设置而不是删除此项的修改

### ISSUE THREAD

**Issue by WhiteElephant-abc** [fifth-light/TouchController#59]
在设置中，点击取消会退出设置而不是撤销更改，建议删除撤销，并将“保存更改”改为“保存更改并退出”，将取消按钮的功能改为撤销按钮的功能

**Comment by WhiteElephant-abc** [comment]
而且由于UI设计，玩家会以为“取消”只会取消此页面的修改，但实际上会删除三个页面的未保存修改

**Comment by fifth-light** [comment]
这个是 YACL 库的逻辑

**Comment by fifth-light** [comment]
![image](https://github.com/user-attachments/assets/b636b95d-d6c1-4842-bfb3-52b6d81bc1a4)
![image](https://github.com/user-attachments/assets/254e7f5f-05f5-4216-ae45-82392c2e6263)
![image](https://github.com/user-attachments/assets/34e5124d-4f5c-4f42-8746-a2fb6f398a0d)
其实把鼠标放到按钮上有相应说明的

**Comment by WhiteElephant-abc** [comment]
触屏基本上没机会看到吧...

**Comment by fifth-light** [comment]
> 触屏基本上没机会看到吧...

我也不能改 YACL 库的逻辑，这方面修改就暂时不考虑了。

**Comment by fifth-light** [comment]
> 而且由于UI设计，玩家会以为“取消”只会取消此页面的修改，但实际上会删除三个页面的未保存修改

其实后来想了想，这个很符合电脑上对话框的逻辑：一个对话框上有很多个标签页，然后标签页下面有确定、取消、应用三个按钮，点击三个按钮其中之一都会对所有标签页的内容进行保存、取消、应用。

有哪个程序的配置界面是分标签页进行保存和撤销的吗？

**Comment by WhiteElephant-abc** [comment]
> 一个对话框上有很多个标签页
> 然后标签页下面有确定、取消、应用三个按钮

但是TC的按钮看起来不像是能一次控制所有标签页，看起来是每个标签页独立的按钮

**Comment by WhiteElephant-abc** [comment]
> 目前的新逻辑是这样：
> 
> * 重置：重置所有设置到默认值
> * 取消：取消所有更改，退出设置界面
> * 保存：保存所有更改并退出
>   依然还是全局的操作，不是分标签页的。
> 
> 如果有未保存的更改，取消时还会有这样一个对话框（目前本地化还没完善）： ![关闭时的警告对话框](https://private-user-images.githubusercontent.com/28196049/399290782-0ba2e492-a06d-49d6-863d-7ea434d2f3ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NjI0NTAsIm5iZiI6MTczNTU2MjE1MCwicGF0aCI6Ii8yODE5NjA0OS8zOTkyOTA3ODItMGJhMmU0OTItYTA2ZC00OWQ2LTg2M2QtN2VhNDM0ZDJmM2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDEyMzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OGFlMTM1M2U1OTA3MmQ0YzU5MGMwMmI0NjFlODQ3YjQ3NWIwYTcyMTUwY2IyMmYzZThhYzY1NDE4YTAwZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sa3VDKuR4_0HR6eVwbog8O82DbtdQ70U2ftclLjqDTI)

那重置能不能改成分标签页的？

**Comment by fifth-light** [comment]
> 那重置能不能改成分标签页的？

我搞个投票吧。我个人是倾向于重置全局设置的。

**Comment by fifth-light** [comment]
#130
