### ISSUE TITLE
“禁用光标锁定”描述错误

### ISSUE THREAD

**Issue by WhiteElephant-abc** [fifth-light/TouchController#60]
_在游戏内禁用光标锁定，从而游戏不会..._
是否应改为：
**从而使游戏不会...**

**Comment by WhiteElephant-abc** [comment]
“在移动端关闭这个选项”也可以改为在移动端 不要开启/请关闭/需要关闭 这个选项

**Comment by fifth-light** [comment]
要不你改改，提个 PR？

**Comment by fifth-light** [comment]
具体文件在[这里](https://github.com/fifth-light/TouchController/blob/0.0/mod/src/main/resources/assets/touchcontroller/lang/zh_cn.json)

**Comment by WhiteElephant-abc** [comment]
提个...Premiere PRO？

**Comment by WhiteElephant-abc** [comment]
您需要复刻此仓库以提出更改。
抱歉，您无法直接编辑此仓库——您需要将其复刻并从那里提出您的更改。

**Comment by fifth-light** [comment]
先 fork（复刻）一份这个仓库，然后修改你自己的副本，最后提交一个 Pull Request（简称PR），请求将你的修改并入我的仓库中即可。

**Comment by WhiteElephant-abc** [comment]
“提出更改建议”

**Comment by fifth-light** [comment]
我个人是因为感觉这个修改起来比较简单。因为我目前工作量比较多，如果不想修改的话也没关系，我之后会修改的。

**Comment by WhiteElephant-abc** [comment]
我装过一个“GitHub中文化工具”所以看不到英文原文

**Comment by WhiteElephant-abc** [comment]
我已经提交了不知道交上去了没

**Comment by fifth-light** [comment]
看到你的提交了，接下来提出一个合并请求（Pull Request），将你的 patch-1 分支合并到我的 0.0 分支

**Comment by fifth-light** [comment]
算了 我提一个Pull Request

**Comment by WhiteElephant-abc** [comment]
![微信图片_20241217135159](https://github.com/user-attachments/assets/ff8f7aaf-bd1c-4697-9188-6fff7ffc069b)
shi'zhe是这个吗

**Comment by fifth-light** [comment]
是这个

**Comment by WhiteElephant-abc** [comment]
交了
