### ISSUE TITLE
单独调整十字键中心键的大小

### ISSUE THREAD

**Issue by fengzhou0w0** [fifth-light/TouchController#82]
![IMG_20241219_104118.jpg](https://github.com/user-attachments/assets/18a7ad58-1112-4dd5-9a6c-31843eee5670)

旧版贴图的十字键怎么调整，中心按钮都做不到和四个方向键大小一致，所以我希望能够单独调整中心按钮大小，从而还原图片的样子。

**Comment by fifth-light** [comment]
![image](https://github.com/user-attachments/assets/ccf90e14-37d7-450b-b69a-6c72c2e150d7)
画上辅助线就可以很清楚的看到，这样其实像素是不对齐的，说明中心的附加按键在你的图片中其实是放大后才能适配十字键的大小。

**Comment by fengzhou0w0** [comment]
不过不细看也看不出来，乐，这下看着舒服了谢了
