### ISSUE TITLE
增加震动反馈强度调节选项

### ISSUE THREAD

**Issue by fengzhou0w0** [fifth-light/TouchController#89]
打开破坏方块震动反馈的功能后，默认是用的是最强烈的震动，震的手有点麻，所以想要降低一点震动反馈强度。

**Comment by fifth-light** [comment]
我的改版启动器是能用就行的策略，不会提供调节功能，这方面就等待未来启动器的官方支持吧。

**Comment by fengzhou0w0** [comment]
好的，调节功能不整也没关系，我请求下次更新改版启动器的时候，把震动强度调小一点就行~
