### ISSUE TITLE
选择框高亮提示

### ISSUE THREAD

**Issue by fengzhou0w0** [fifth-light/TouchController#94]
![Screenshot_2024-12-22-01-39-53-186_com.mojang.minecraftpf.jpg](https://github.com/user-attachments/assets/032e305f-e392-4b50-8245-39d34bf147f8)

基岩版在调整视角时，手指停留的位置的方块表面会发亮。这个和震动功能一样是方便手机玩家操作的，可以添加一波~

**Comment by fifth-light** [comment]
我之前就想这么做，但是发现不知道如何渲染这种效果，最后就决定还是用java版的边框效果吧。

如果有谁知道做可以指导一下，我是不会做了。
