### ISSUE TITLE
潜行时攀爬可以悬空

### ISSUE THREAD

**Issue by WhiteElephant-abc** [fifth-light/TouchController#96]
![image](https://github.com/user-attachments/assets/8a6cab5e-0e03-4a3f-b869-994b317842f8)
在藤蔓上拖动方向键即可

**Comment by fifth-light** [comment]
再具体一些，你是什么意思？在 Java 版中，攀爬时潜行可以悬空是原版行为。

**Comment by WhiteElephant-abc** [comment]
是TC，在java原版中应该不行...（我测一下吧）

**Comment by WhiteElephant-abc** [comment]
经测试，是java原版行为
