### ISSUE TITLE
自动疾跑

### ISSUE THREAD

**Issue by WhiteElephant-abc** [fifth-light/TouchController#98]
类似一些手游，将摇杆拖到顶再继续拖动便可触发疾跑（这样便于一些不适应双击w疾跑的电脑版玩家，并且摇杆相比于按键更难双击w）

**Comment by WhiteElephant-abc** [comment]
实测国际基岩版1.21.51.02拥有此功能，即将摇杆拖到顶触发疾跑

**Comment by WhiteElephant-abc** [comment]
> > 即将摇杆拖到顶触发疾跑
> 
> 你说的是“使用摇杆冲刺”这个选项吧

是基岩版的选项吗？我反正在基岩版里可以这么疾跑，可能之前我开过这个选项

**Comment by WhiteElephant-abc** [comment]
建议合并到 #105

**Comment by fifth-light** [comment]
> 建议合并到 #105

分开来比较好，这个 issue 功能相对于 #105 比较独立。

> 是基岩版的选项吗？

具体来说是这个选项：

![“使用摇杆冲刺”选项](https://github.com/user-attachments/assets/4128cd49-7fc8-4c24-9523-c7185b0fe10f)

**Comment by WhiteElephant-abc** [comment]
> > 建议合并到 #105
> 
> 分开来比较好，这个 issue 功能相对于 #105 比较独立。
> 
> > 是基岩版的选项吗？
> 
> 具体来说是这个选项：
> 
> ![“使用摇杆冲刺”选项](https://private-user-images.githubusercontent.com/28196049/398059446-4128cd49-7fc8-4c24-9523-c7185b0fe10f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MzEzNjEsIm5iZiI6MTczNDkzMTA2MSwicGF0aCI6Ii8yODE5NjA0OS8zOTgwNTk0NDYtNDEyOGNkNDktN2ZjOC00YzI0LTk1MjMtYzcxODViMGZlMTBmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA1MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NzdlNGRhOGQyMzhhYjg4OGJiNjJkMTcxMjU1NWY2ZDRmN2MxNTAwMjc0YThhMzYyNGYwMzMzYzY3ZmU0MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J2il5JMB3XBJScL7vd-snW6iJ5AieawWkcYrCvdhvpU)

那就把这个选项加到TC里吧

**Comment by fifth-light** [comment]
commit 3b9bfae2c9c6515e93811abb37173f610ead2cc6
